name: shopping_app_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/select.mp3
    - assets/sounds/deselect.mp3
    - assets/demo/shopping_list_demo.mp4
